### ISSUE TITLE
CC2531 as a Zigbee Sensor

### ISSUE THREAD

**Issue by splitice** [zigbeer/zigbee-shepherd#5]
Say I wanted the CC2531 to function as a (high power) Zigbee Sensor.

Do you know if this be possible?

**Comment by simenkid** [comment]
Hi @splitice, you might need a [CC2591](http://www.ti.com/product/CC2591) fron-end to boost your zigbee sensor. Unfortunately, it seems not easy to integrate 2591 with 2531.

**Comment by splitice** [comment]
Thanks yes, we came to a similar oppinion over the weekend that th CC2531 is not really suited for running as an End Device.

We are currently looking at the Digi XBee and trying to get it to work with a CC2531 as Coordinator. Breaking out the sniffer at the moment but not having much luck yet. Not seeing any device join.

Any thoughts? I'd be happy to PR any support or fixes we introduce (along side some already made).

**Comment by splitice** [comment]
It looks like the problem is specifically with the values returned by the TI CC531.
Sometimes we see a tcDeviceInd with values from the xbee device in it, but never a Device Join.

To me (with my limited experience) it looks like the Xbee does not like something in the packet from the TI. Not sure if you have any experience here. A pcap file is attached.

[capture-xbees2-tiznp.zip](https://github.com/zigbeer/zigbee-shepherd/files/837419/capture-xbees2-tiznp.zip)

**Comment by jackchased** [comment]
Hi @splitice, sorry for the late response.

We do not understand the problem here, because we have no experience on Xbee.
And I look the pcap file only see `'Orphan Notification'`, but without capture `'Association Request'` and `'Association Response'` info. I'm not sure Xbee device is real join the network.

You can open PR or issues to us, if you have any progress on this issue. Thank you!

![image](https://cloud.githubusercontent.com/assets/14177449/24035448/9e778efa-0b30-11e7-9f0b-7f7dfef1f093.png)

**Comment by splitice** [comment]
Unfortunately we have come to the conclusion that the XBee hardware is not compatible with the CC2531ZNP. I was not able to with certainty identify the cause of the incompatibility.

Thank you for your assistance however.

We have resolved this by using the CC2530/CC2531 as a End Device.

**Comment by Nebukadneza** [comment]
This is long closed, but … can you elaborate a bit on using CC2530 as end devices? There seems to be pretty little documentation floating around. Even a few pointers would help greatly~.

Thanks,
-Dario
