### ISSUE TITLE
don't trigger 'ind' event 

### ISSUE THREAD

**Issue by amigomcu** [zigbeer/zigbee-shepherd#9]
hi all,
when i start permitJoin device, i can see my device have been add PAN network.
but it don't trigger 'ind' event and  shepherd.list() return only Coordinator.
could you give me some suggestion with this?

I'm a beginner at full-stack iot development.
how to use the utilizes debug module on windows(win 7 64bit)

hw. cc2531 usb dongle.
fw. cc-znp

**Comment by splitice** [comment]
We have seen similar issues, usually restarting the software, reseting the device or ZNP dongle does the job.

Often this happens when the software is restarted. Our current operating theory is that the ZNP dongle thinks the device is joined in the firmware. I have not been able to find a place where Zigbee Shepherd asks  for a list of joined devices.

Perhaps executing a ZNP reset before start / init would solve the problem?

**Comment by splitice** [comment]
Internal discussion reveals:
 - Issue could be due to application close when allowing join, this can allow device to join when ZS not running. Never sending off any event.
 - Regardless, no events logged during period that ZS not online, therefore not aware of state.

Our proposed solution we are toying with at the moment is on-init to use assocFindDevice and assocCount to iterate the ZNP's status and mark devices as online/offline in devbox (the db).

Would love some feedback from the Zigbee Shepherd guys.

**Comment by splitice** [comment]
That would be limited to associations on the coordinator, it wouldn't pick up on associations on routers in the network.

Perhaps the approach described here: http://electronics.stackexchange.com/questions/199078/how-do-i-maintain-an-active-list-of-zigbee-devices-in-a-han

**Comment by splitice** [comment]
Initial implementation in our fork, cursory evaluation in our lab looks positive.

**Comment by splitice** [comment]
One outstanding issue with our patch is that IAS status changes are not being handled received by node.

We can communicate with the device just fine (e.g enrol to events), and the events are sent (packet sniffer confirmed), just nothing in ZS (DEBUG=*).

**Comment by simenkid** [comment]
Hi @amigomcu.  you can try the [node-env](https://www.npmjs.com/package/cross-env) out to have the environment variable been set correctly in windows.
1. Under your project folder, `npm install cross-env --save-dev`
2. Run the server with cross-env: `cross-env DEBUG=zigbee-shepherd* node server.js`

Could you paste your code to us? Let's see if anything went wrong with the 'ind' issue.  Thanks!

**Comment by simenkid** [comment]
Hi @splitice, I think your speculation on these two points is sensible:

* Issue could be due to application close when allowing join, this can allow device to join when ZS not running. Never sending off any event.
* Regardless, no events logged during period that ZS not online, therefore not aware of state.

My proposal is to have a handler to always disallow device joining when the server shutting down:
```js
process.on('exit', function () {
     shepherd.permitJoin(0);
})`
```
But I wonder that this would not fully solve the problem, there is still a **very little chance** that a device comes into the network when ZS is not in the ready state and the ZNP dongle still opens for joining.

**Comment by splitice** [comment]
That still doesnt help as existing devices will stay joined during reboot, they will never re-join as they are in fact still joined. You could do a hardware reset instead. Still, it's not all that reliable and for some devices rejoining takes hours.

Our current method of doing an network scan is holding up well. Further work is required as per the TODO though in case we loose the database, or a new device joins while the software isnt running.
